column_width = 120
indent_width = 4
indent_type  = "Spaces"             # Tabs or Spaces
line_endings = "Unix"               # Unix(LF) or Windows(CRLF)
quote_style  = "AutoPreferSingle"   # AutoPreferDouble AutoPreferSingle ForceDouble ForceSingle
